### ISSUE TITLE
Roadmap / Things to add 

### ISSUE THREAD

**Issue by ustaalon** [ustaalon/LethalCompany.LaserControl#3]
**Turrets:**
- [x] Can control turret's direction and fire with them (initial release)
- [x] Can turn off the turret for a few seconds (initial release)
- [x] Can buy laser pointer via ship's store (initial release)
- [x] When using the laser pointer as a controller - it will use more battery (initial release)
- [x] After a few seconds of usage, the turret and laser pointer will stop working (the turret will turn off for a few seconds) (v0.1.4)
- [x] Change laser pointer logic to Mouse Right click to shoot (v0.1.4)
- [x] Increasing turret turn speed when bonded with the laser pointer (v0.1.4)
- [ ] Control multiple turrets

**Landmines:**
- [x] Can detonate landmines (initial release)

**Monsters:**
- [ ] Blinding an enemy when pointing at them (to eyes?)
- [ ] Thumper follows the laser
- [ ] Option to deal with beehives?

**Compatibility:**
- [x] Fixed compatibility with ReservedSlot (v0.1.4)
- [x] Fixed compatibility with AdvancedCompany (v0.1.4)
- [ ] Check compatibility with Symbiosis
- [ ] Check compatibility with FairAI

**Misc:**
- [x] Host configuration for laser pointer abilities (initial release)
- [x] Configuration battery drain (v0.1.4)
- [x] Reduce the amount of logs for the user (v0.1.5)
- [x] Price of the laser pointer can be adjusted via the config menu (v0.1.6)
